### ISSUE TITLE
Problème lancement 

### ISSUE THREAD

**Issue by rafale17** [hopollo/Wakfarm#11]
Bonjour, 
Tous d'abord je tiens à vous féliciter de votre travail !
Cependant j'ai un petit problème, je n'arrive pas à lançer ImageSearch. Je clique dessus mais rien ne se passe. J'ai comme vous l'avez demander installer les pack x64 et x86 ^^

Bonne continuation dans votre programmation
 Cordialement

**Comment by hopollo** [comment]
Bonjour,

Merci pour vos retours, le seul fichier à manipuler pour faire fonctionner le script est uniquement le WakFarm.au3 :) cependant ImageSreach doit figurer dans son dossier racine si il n'a pas été compilé.

N'hésitez pas à me faire part de vos retours.
