### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by blifont** [hopollo/Wakfarm#13]
Hey man, I managed to run the script, but I have a few problems, the program only cuts the crop, but don´t collects seeds and sometimes doesn´t even work. So I was wondering if you could give me any advice on what to do or if you can make a tutorial to know how to use the program properly.

**Comment by hopollo** [comment]
Hi, the best option is to tweak (inside the code itself) pixels and of course redoo images to detects :)

**Comment by blifont** [comment]
ok, i´ll try, thx for the answer, apreciate it.
