### ISSUE TITLE
Eplication pour chercher l'image

### ISSUE THREAD

**Issue by rafale17** [hopollo/Wakfarm#14]
Salut je reviens vers toi pour essayer de comprendre comment marche le programme, surtout comment puis-je mettre l'image afin qu'il l'a détecte sur le jeu…
Merci pour tes conseils
Et à très bientôt ;)

**Comment by hopollo** [comment]
Salut, désolé du retard.

Bon pour faire trouver des images dans ton jeu au programme, il faut prendre un screenshot de ce que tu veux farm mob/ressource (la plus petite et originale/unique à ta cible possible pour éviter qu'il confonde avec qqch d'autre)

**Comment by rafale17** [comment]
Ok d'acc et après je la mets dans quoi ? 🤔
Et une question le bot arrive à passer le cap'chat ?

**Comment by hopollo** [comment]
Les images ce situent comme dans le dossier du project au téléchargement (.../targets/current)
Le script ne prend pas en charge les captcha non.

**Comment by rafale17** [comment]
![20200221_111857](https://user-images.githubusercontent.com/54121566/75028430-83be2a80-54a0-11ea-9348-c8a6558e58db.jpg)

Voilà j'ai mis l'image dans le dossier comme tu as dis, ouvert le luncher et voilà ce qu'il se passe....
Que dois je faire ?

**Comment by hopollo** [comment]
Le spam de message wakfu OK n'est pas normal, il devrait faire "updater Ok", "wakfu Ok" et commencer les manipulations de dezoom etc etc. Après relecture rapide du code, je pense au probleme suivant. Le launcher n'est probablement pas resté ouvert pour que le script détecte les deux fenetres afin de passer à la suite. Sinon un contourneent (bricolage) simple est à effectuer comme : `L.188 : Local $update = True` par exemple pour passer cette étape vu que le jeu est bien détecté d'apres l'image.

**Comment by hopollo** [comment]
No more updates about it
