### ISSUE TITLE
How to run it HALP! :D

### ISSUE THREAD

**Issue by Neni1994** [hopollo/Wakfarm#15]
Hello!!

I have an issue I'm completly green when it comes to codeing... It's not lazyness I just don't know what to do. I have the Github application for windows I dropped files and now im stuck on what to do.... Can you help me please? 

Got it I'm sorry for writing! I can run it now the fun stuff which is adding everything! :D

**Comment by hopollo** [comment]
Good to know you managed to run it ! :D GLHF
