### ISSUE TITLE
Le bot ne veut pas récolter

### ISSUE THREAD

**Issue by Nagarack** [hopollo/Wakfarm#16]
Salut !
J'ai réussi a faire fonctionner le bot, il clique bien sur les plantations mais n'arrive pas a sélectionner le cut/harvest...

Une idée ?

**Comment by Jimmylamz** [comment]
can you share your working files please. i cant make it move. ImageSearch won't load

**Comment by hopollo** [comment]
> Salut !
> J'ai réussi a faire fonctionner le bot, il clique bien sur les plantations mais n'arrive pas a sélectionner le cut/harvest...
> 
> Une idée ?

Il faudrait essayer de modifier les pixels/images qu'il cherche en fonction de ton jeu uniquement, ils ont ajoutés des variantes de couleurs en fonction de la méteo etc pour compliquer les détections de ce genre

**Comment by hopollo** [comment]
> can you share your working files please. i cant make it move. ImageSearch won't load

It's already given with working files, it worked (back then) perfectly on my side that's why i shared it lol, got lvl 67 on "mob harvester" with that, anyway you have to update pixels/images from your own game to make it work, my files will not be the same as your, if that make sence

**Comment by Mass191** [comment]
[WakFarm-master.zip](https://github.com/user-attachments/files/19894057/WakFarm-master.zip)
