### ISSUE TITLE
Comment compiler ?

### ISSUE THREAD

**Issue by MedCy1** [hopollo/Wakfarm#17]
Hey salut, je n'arrive pas a compiler, si quelqu'un pouvais m'expliquer ce serais cool
Merci

**Comment by hopollo** [comment]
Faut télécharger/Installer AutoIt et click droit -> compiler sur le ".au3" mais il faudra adapter le code car plus à jours depuis plusieurs années (évolution du jeu) et les couleurs de pixels également.

**Comment by MedCy1** [comment]
oki merci ^^
