### ISSUE TITLE
Initial includes not in repo

### ISSUE THREAD

**Issue by Gonzo107** [hopollo/Wakfarm#3]
The initial includes 
`#include <ImageSearch.au3>
#include <FileConstants.au3>
#include <MsgBoxConstants.au3>
#include <WinAPIFiles.au3>`

are not in the repo, pls add

and i too would like you to explain me this script in natural language, i'd like to work in it, thanks

P.D: i understand a little bit of french.

**Comment by ichsphon** [comment]
is a pixelbot

**Comment by hopollo** [comment]
ImageSearch.au3 is now included, others are for default on AutoIt :)
