### ISSUE TITLE
I dont know how define a target

### ISSUE THREAD

**Issue by Romarikon** [hopollo/Wakfarm#5]
You can give more specific instruccions?

**Comment by kosidk** [comment]
Yeah, i'm with you. I'd like more instruccions for newbies like me ^^

**Comment by hopollo** [comment]
Hi guys, the Issue section is not meant to be used for this kind of support i guess, anyway can you be more precise about what you don't undrestand ? Edit the target.png first to what you need if that make sence

**Comment by kosidk** [comment]
Oh, sorry. I'm literally new to github and I thought i could use this section to look for help.  My problem is that... I literally don't know what to do with the "target.png"

**Comment by hopollo** [comment]
screenshot your game (in front of the ressources/mobs) you want to harvest, focus it by geting a little part (squarre) of it and replace the target.png

**Comment by hopollo** [comment]
I'm gonna work on the wiki section to explain how to use it, closing the thread for now
