### ISSUE TITLE
Cant copile 

### ISSUE THREAD

**Issue by fuwsion** [hopollo/Wakfarm#7]
Dude i was compiling the au3 script with autoit 
but it shown like this 
![image](https://user-images.githubusercontent.com/39260070/39986146-ffed03e8-578a-11e8-998e-d4ee6950463b.png)

**Comment by hopollo** [comment]
Ok going to add the link to download Microsoft Visual C++ 2010 SP1 Redistributable Package

**Comment by fuwsion** [comment]
ive alredy install that package 
but still cant compile 
can you share the .exe or compiled version

**Comment by hopollo** [comment]
It's not worth it, the program won't work properly because we don't have the same screen size, game window position and so on...

**Comment by fuwsion** [comment]
so what should i do man ?

**Comment by hopollo** [comment]
Make sure to get the new update, run script instead of compile for now
