### ISSUE TITLE
Open source not only for Windows?

### ISSUE THREAD

**Issue by zenogears** [hopollo/Wakfarm#8]
Hi! I found yours project, and i think it is alives.
But how i can use it on other operation systems?
For example, Linux?
May be there is a chance to create project on something crossplatform programming languich?

**Comment by hopollo** [comment]
Hi zenogears,

Sadly i think AutoIt is not meant for crossplatfrom.
But it maybe should work with wine ? i never tried :)

**Comment by zenogears** [comment]
Yes, i think it can works by wine. But client for it need be started by wine too?
It is hentai.
I think it will be more good to rewrite project using python for example and make it truly crossplatform. But thanks for comment :)

**Comment by hopollo** [comment]
Hi, 

I think yes the client must run with wine to let Wakfarm gather CLASS, Window infos and proceed from his default environment (windows). (Pixels search should work but you might not be able to go that far with the program, i don't think he's gonna find the client to continue on his steps). If that make sence...

For the python idea idk i'm not intrested at all about this language, for me it look weird and not sexy at all i guess, but maybe in "a far" future if i need to learn it :)
